# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  python311:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install native dependencies
      run: |
        bash install_native_deps.sh
    - name: Install poetry
      run: pipx install poetry
    - uses: actions/setup-python@v4
      name: Install python dependencies
      with:
        python-version: '3.11'
        cache: 'poetry'
    - run: poetry lock
    - run: poetry install
    - run: poetry run black --check src tests
    - run: poetry run ruff .
    - name: Test with Pytest
      run: |
        ulimit -s unlimited
        poetry run pytest

  python38:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install native dependencies
      run: |
        bash install_native_deps.sh
    - name: Install poetry
      run: pipx install poetry
    - uses: actions/setup-python@v4
      name: Install python dependencies
      with:
        python-version: '3.8'
        cache: 'poetry'
    - run: poetry lock
    - run: poetry install
    - run: poetry run black --check src tests
    - run: poetry run ruff .
    - name: Test with Pytest
      run: |
        ulimit -s unlimited
        poetry run pytest
